public class BigOSingleLoop {
    public static void main(String[] args) {
        long numberOfOperations=0;
        int n=10000;// size of  Data
        int m=500;
        long startTime;
        long endTime;
        System.out.println("Input size n is = "+ n);

        // Task 1 Single Loop................... O(n)


        // Task 2 Nested Loops...................

        // Task 2 End...................
// ......................................................................................................
        // Task 3 Three Nested Loops...................

        // Task 3 Triple Nested Loops...................

        // Task 3 End...................
// ......................................................................................................
        // Task 4 N and M Nested Loops  O(n*m)...................


        // Task 4 End...................

        // Task 4.5 N and M Consecutive Loops O(n+m)...................

        // Task 4.5 End...................

        // Task 5 Logarithmic Complexity...................

        // Task 5 End...................*/
    }
}